# Generated by Django 5.0.2 on 2024-06-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cook', '0004_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='media/profile_pictures/default.png', upload_to='profile_pictures/'),
        ),
    ]
