# Generated by Django 5.0.2 on 2024-05-28 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categories', models.CharField(help_text='Eg: Occasions, Cuisines, Meals', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recipes/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='recipes/videos/')),
                ('preparation_time', models.CharField(max_length=100)),
                ('cooking_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='stream',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='post.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recipes/steps/')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='post.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='likes',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='post.recipe'),
        ),
        migrations.AddField(
            model_name='stream',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.recipe'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
