# Generated by Django 5.0.2 on 2024-05-28 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_recipe_remove_stream_post_remove_likes_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 28, 14, 29, 7, 754176, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
