# Generated by Django 5.0.2 on 2024-06-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_recipe_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='average_rating',
            field=models.IntegerField(default=0),
        ),
    ]
